import threading
from dataclasses import dataclass

from PySide6.QtCore import (
    QObject,
    Signal,
)

from src.EmbeddingCache import EmbeddingCache


@dataclass(frozen=True)
class _EmbeddingCacheRequest:
    """
    Immutable request for all compatible cached embeddings belonging
    to one recording.

    request_id is generated by ControlWindow so a result from a
    previously selected recording can be discarded safely.
    """

    request_id: int
    recording_id: str
    pipeline_hash: str
    embedding_name: str


class EmbeddingCacheWorker(QObject):
    """
    Read recording-level embedding cache contents away from the Qt GUI
    thread.

    Only the newest pending request is retained. Rapidly switching
    recordings therefore does not build a queue of obsolete cache scans.
    """

    loaded = Signal(
        int,
        object,
    )

    failed = Signal(
        int,
        str,
    )

    def __init__(
        self,
        cache: EmbeddingCache,
        parent=None,
    ):
        super().__init__(parent)

        if not isinstance(
            cache,
            EmbeddingCache,
        ):
            raise TypeError(
                "cache must be an EmbeddingCache"
            )

        self.cache = cache

        self._condition = threading.Condition()
        self._pending_request = None
        self._stopping = False

        self._thread = threading.Thread(
            target=self._run,
            name="embedding-cache-worker",
            daemon=True,
        )

        self._thread.start()

    # ======================================================
    # Public interface
    # ======================================================

    def request(
        self,
        request_id: int,
        recording_id: str,
        pipeline_hash: str,
        embedding_name: str,
    ):
        request = _EmbeddingCacheRequest(
            request_id=request_id,
            recording_id=recording_id,
            pipeline_hash=pipeline_hash,
            embedding_name=embedding_name,
        )

        with self._condition:

            if self._stopping:
                return

            self._pending_request = request
            self._condition.notify()

    def shutdown(
        self,
    ):
        with self._condition:
            self._stopping = True
            self._pending_request = None
            self._condition.notify()

    # ======================================================
    # Worker loop
    # ======================================================

    def _run(
        self,
    ):
        while True:

            with self._condition:

                while (
                    not self._stopping
                    and self._pending_request is None
                ):
                    self._condition.wait()

                if self._stopping:
                    return

                request = self._pending_request
                self._pending_request = None

            try:
                embeddings = self.cache.list_embeddings(
                    recording_id=request.recording_id,
                    pipeline_hash=request.pipeline_hash,
                    embedding_name=request.embedding_name,
                )

            except Exception as exc:

                if self._is_stopping():
                    return

                if self._has_newer_request(
                    request.request_id
                ):
                    continue

                self.failed.emit(
                    request.request_id,
                    f"{type(exc).__name__}: {exc}",
                )

                continue

            if self._is_stopping():
                return

            if self._has_newer_request(
                request.request_id
            ):
                continue

            self.loaded.emit(
                request.request_id,
                embeddings,
            )

    def _has_newer_request(
        self,
        request_id,
    ):
        with self._condition:
            return (
                self._pending_request is not None
                and self._pending_request.request_id
                > request_id
            )

    def _is_stopping(
        self,
    ):
        with self._condition:
            return self._stopping
