# EmbeddingsCreator
# This pipeline link accepts AudioBuffers and runs them through a pre-loaded ONNX embedding model. The resulting model outputs are not saved; after inference completes, the original AudioBuffer is passed to the next link.
#
# AudioBuffers are assumed to already contain mono float audio at the sample rate and length required by the configured model.

from dataclasses import dataclass
from pathlib import Path
import threading

import numpy as np
import onnxruntime as ort

from src.AudioBuffer import AudioBuffer
from src.PipelineLink import PipelineLink

ort.preload_dlls(directory="")


@dataclass
class _EmbeddingRuntime:
    """
    Shared ONNX runtime state.

    Multiple EmbeddingsCreator pipeline links can share one model session while
    keeping independent callback/previous pointers. The lock serialises calls
    into the shared session when batch and interactive pipelines run at the
    same time.
    """

    session: object
    input_name: str
    input_shape: object
    input_type: str
    inference_lock: threading.Lock


class EmbeddingsCreator(PipelineLink):
    """Run an ONNX embedding model on AudioBuffer objects and attach results.

    Loads an ONNX model via onnxruntime and performs inference on incoming
    AudioBuffers, storing outputs under audio.embeddings[embedding_name].

    A creator can also produce another callback-pipeline link that shares the
    same ONNX runtime. This is used by interactive embedding requests so they
    remain callback pipelines without loading a second model session.
    """

    def __init__(
        self,
        model_path,
        use_cuda=True,
        embedding_name="perch_v2",
        _shared_runtime=None,
        pipeline_hash_override=None,
    ):
        """Initialize the embeddings runtime.

        Args:
            model_path (str): Path to the ONNX model file.
            use_cuda (bool): Prefer CUDAExecutionProvider if available.
            embedding_name (str): Key name under which outputs are stored on
                audio.embeddings.
            _shared_runtime: Internal runtime used by shared callback links.
            pipeline_hash_override: Optional canonical pipeline hash to stamp
                onto embeddings generated by an alternate callback graph.

        Raises:
            FileNotFoundError: If model_path does not exist when creating a new
                runtime.
            ValueError: If the model has an unexpected number of inputs.
        """
        super().__init__()

        self.embedding_name = embedding_name
        self.model_path = model_path
        self._pipeline_hash_override = (
            None
            if pipeline_hash_override is None
            else str(pipeline_hash_override)
        )

        if _shared_runtime is None:
            self._runtime = self._create_runtime(
                model_path=model_path,
                use_cuda=use_cuda,
            )
        else:
            if not isinstance(
                _shared_runtime,
                _EmbeddingRuntime,
            ):
                raise TypeError(
                    "_shared_runtime must be an _EmbeddingRuntime"
                )

            self._runtime = _shared_runtime

        # Preserve the public attributes used by the rest of the existing
        # codebase.
        self.session = self._runtime.session
        self.input_name = self._runtime.input_name
        self.input_shape = self._runtime.input_shape
        self.input_type = self._runtime.input_type

    # ======================================================
    # Shared runtime
    # ======================================================

    @staticmethod
    def _create_runtime(
        model_path,
        use_cuda,
    ):
        model_path_object = Path(model_path)

        if not model_path_object.is_file():
            raise FileNotFoundError(
                f"ONNX model does not exist: {model_path_object}"
            )

        available_providers = ort.get_available_providers()

        if (
            use_cuda
            and "CUDAExecutionProvider" in available_providers
        ):
            providers = [
                "CUDAExecutionProvider",
                "CPUExecutionProvider",
            ]
        else:
            providers = [
                "CPUExecutionProvider",
            ]

        session = ort.InferenceSession(
            str(model_path_object),
            providers=providers,
        )

        model_inputs = session.get_inputs()

        if len(model_inputs) != 1:
            raise ValueError(
                "EmbeddingsCreator expects the ONNX model to have "
                f"one input, but found {len(model_inputs)}"
            )

        model_input = model_inputs[0]

        return _EmbeddingRuntime(
            session=session,
            input_name=model_input.name,
            input_shape=model_input.shape,
            input_type=model_input.type,
            inference_lock=threading.Lock(),
        )

    def shared_runtime_link(
        self,
        pipeline_hash_override=None,
    ):
        """
        Return a new EmbeddingsCreator pipeline link sharing this model runtime.

        The returned object has independent callback and previous pointers, so
        it can participate in another callback graph without rewiring the batch
        pipeline.
        """

        return EmbeddingsCreator(
            model_path=self.model_path,
            embedding_name=self.embedding_name,
            _shared_runtime=self._runtime,
            pipeline_hash_override=pipeline_hash_override,
        )

    # ======================================================
    # Pipeline configuration
    # ======================================================

    def configuration_parameters(self) -> dict[str, any]:
        """Return configuration parameters affecting the embedding output."""
        return {
            "model_path": self.model_path,
        }

    def get_config_hash(self):
        """
        Return the canonical embedding-pipeline hash.

        Normal batch links derive this from their registered upstream graph.
        An interactive link can explicitly inherit the batch graph's hash while
        still using its own callback graph for execution.
        """

        if self._pipeline_hash_override is not None:
            return self._pipeline_hash_override

        return super().get_config_hash()

    # ======================================================
    # Pipeline input
    # ======================================================

    def next_audio(self, audio):
        """Run the ONNX model and forward the AudioBuffer to the callback.

        If the requested embedding is already present (for example because an
        upstream EmbeddingCacheLoader found it), inference is skipped and the
        buffer is simply forwarded.
        """

        if not isinstance(audio, AudioBuffer):
            raise TypeError(
                "EmbeddingsCreator expects an AudioBuffer"
            )

        if self.embedding_name in audio.embeddings:
            if self.callback is not None:
                self.callback.next_audio(audio)
            return

        print("computing")

        model_input = self._prepare_input(
            audio
        )

        with self._runtime.inference_lock:
            outputs = self.session.run(
                None,
                {
                    self.input_name: model_input,
                },
            )

        if len(outputs) == 0:
            raise RuntimeError(
                "The ONNX model returned no outputs"
            )

        pipeline_hash = self.get_config_hash()

        audio.embeddings[self.embedding_name] = {
            "values": np.asarray(outputs[0]),
            "pipeline_hash": pipeline_hash,
            "metadata": {
                "input_name": self.input_name,
                "input_shape": self.input_shape,
                "output_index": 0,
            },
            "loaded_from_cache": False,
        }

        if self.callback is not None:
            self.callback.next_audio(audio)

    def _prepare_input(
        self,
        audio: AudioBuffer,
    ) -> np.ndarray:
        waveform = np.asarray(
            audio.waveform,
            dtype=np.float32,
        )

        if waveform.size == 0:
            raise ValueError(
                "Cannot run inference on an empty AudioBuffer"
            )

        # Convert internal mono shape (samples, 1) to (samples,).
        if waveform.ndim == 2:
            if waveform.shape[1] != 1:
                raise ValueError(
                    "EmbeddingsCreator expects mono audio, but received "
                    f"{waveform.shape[1]} channels"
                )

            waveform = waveform[:, 0]

        elif waveform.ndim != 1:
            raise ValueError(
                "AudioBuffer waveform must have shape "
                "(samples,) or (samples, 1)"
            )

        valid_samples = min(
            audio.valid_samples,
            len(waveform),
        )

        waveform = waveform[:valid_samples]

        expected_samples = self._get_expected_samples()

        if expected_samples is not None:
            if len(waveform) < expected_samples:
                waveform = np.pad(
                    waveform,
                    (
                        0,
                        expected_samples - len(waveform),
                    ),
                )

            elif len(waveform) > expected_samples:
                raise ValueError(
                    f"AudioBuffer contains {len(waveform)} samples, "
                    f"but the model expects {expected_samples}"
                )

        return np.ascontiguousarray(
            waveform[np.newaxis, :],
            dtype=np.float32,
        )

    def _get_expected_samples(
        self,
    ):
        if len(self.input_shape) != 2:
            return None

        sample_dimension = self.input_shape[1]

        if isinstance(
            sample_dimension,
            (int, np.integer),
        ):
            return int(
                sample_dimension
            )

        return None
