import threading
from dataclasses import dataclass

from PySide6.QtCore import (
    QObject,
    Signal,
)

from src.AudioBuffer import AudioBuffer
from src.AudioReader import AudioReader


@dataclass(frozen=True)
class _BrowsingAudioRequest:
    """
    Immutable description of one requested browsing chunk.

    request_id is generated by ControlWindow. It lets the GUI
    distinguish the newest request from an older result that may
    finish later.
    """

    request_id: int
    packet: object
    chunk_index: int
    start_s: float
    duration_s: float


class BrowsingAudioLoader(QObject):
    """
    Load browsing audio away from the Qt GUI thread.

    The loader owns one background Python thread and keeps at most
    one pending request. If the user moves the slider several times
    while a load is already running, newer pending requests replace
    older pending requests instead of building an unbounded queue.

    A request that is already being read cannot be cancelled, so its
    result may still arrive. ControlWindow uses request_id to discard
    such stale results.
    """

    loaded = Signal(
        int,
        object,
    )

    failed = Signal(
        int,
        str,
    )

    def __init__(
        self,
        audio_reader: AudioReader,
        parent=None,
    ):
        super().__init__(parent)

        self.audio_reader = audio_reader

        self._condition = threading.Condition()
        self._pending_request = None
        self._stopping = False

        self._thread = threading.Thread(
            target=self._run,
            name="browsing-audio-loader",
            daemon=True,
        )

        self._thread.start()

    # ======================================================
    # Public interface
    # ======================================================

    def request(
        self,
        request_id: int,
        packet,
        chunk_index: int,
        start_s: float,
        duration_s: float,
    ):
        """
        Request one source-audio window.

        Only the newest request waiting to be processed is retained.
        This makes rapid scrubbing coalesce naturally.
        """

        request = _BrowsingAudioRequest(
            request_id=request_id,
            packet=packet,
            chunk_index=chunk_index,
            start_s=start_s,
            duration_s=duration_s,
        )

        with self._condition:

            if self._stopping:
                return

            self._pending_request = request
            self._condition.notify()

    def shutdown(
        self,
    ):
        """
        Stop accepting work and wake the worker so it can exit.

        The thread is a daemon and shutdown deliberately does not
        block the GUI waiting for an in-progress CARACAL read.
        """

        with self._condition:
            self._stopping = True
            self._pending_request = None
            self._condition.notify()

    # ======================================================
    # Worker loop
    # ======================================================

    def _run(
        self,
    ):
        while True:

            with self._condition:

                while (
                    not self._stopping
                    and self._pending_request is None
                ):
                    self._condition.wait()

                if self._stopping:
                    return

                request = self._pending_request
                self._pending_request = None

            try:
                waveform, sample_rate = (
                    self.audio_reader.read(
                        packet=request.packet,
                        start_s=request.start_s,
                        duration_s=request.duration_s,
                    )
                )

                audio_buffer = AudioBuffer(
                    packet=request.packet,
                    waveform=waveform,
                    sample_rate=sample_rate,
                    start_offset_s=request.start_s,
                    valid_samples=len(waveform),
                    left_context_samples=0,
                    right_context_samples=0,
                    chunk_index=request.chunk_index,
                )

            except Exception as exc:

                if self._is_stopping():
                    return

                self.failed.emit(
                    request.request_id,
                    f"{type(exc).__name__}: {exc}",
                )

                continue

            if self._is_stopping():
                return

            self.loaded.emit(
                request.request_id,
                audio_buffer,
            )

    def _is_stopping(
        self,
    ):
        with self._condition:
            return self._stopping
