name: Build Docs

on:
  push:
    branches: 
       - dev
       - docs-deploy
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  docs:
    runs-on: ubuntu-latest

    environment: 
      name: github-pages 
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - uses: actions/checkout@v6

      - name: Install Doxygen graphviz
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: Build docs
        run: doxygen Doxyfile

      - name: Configure Pages
        uses: actions/configure-pages@v5 
             
      - name: Upload docs
        uses: actions/upload-pages-artifact@v4
        with:
          path: docs/html

      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4

      - name: Make artifact
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-html
          path: docs/html
